# Generated by Django 4.2.7 on 2026-03-01 07:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('units_allocated', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'allocation_details',
            },
        ),
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('bank_type', models.CharField(choices=[('GOVT', 'Government'), ('PRIVATE', 'Private'), ('NGO', 'Non-Profit'), ('RED_CROSS', 'Red Cross')], max_length=20)),
                ('contact_number', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('max_storage_capacity', models.PositiveIntegerField(help_text='Maximum units the bank can store', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('certification_date', models.DateField(blank=True, null=True)),
                ('certification_expiry', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'BLOOD_BANK'}, on_delete=django.db.models.deletion.CASCADE, related_name='bloodbank_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blood Banks',
                'db_table': 'blood_banks',
            },
        ),
        migrations.CreateModel(
            name='DemandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_type', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], max_length=3)),
                ('units_requested', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('units_fulfilled', models.PositiveIntegerField(default=0)),
                ('request_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('required_by_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PARTIALLY_FILLED', 'Partially Filled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='1=Low, 5=Critical', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('purpose', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Demand History',
                'db_table': 'demand_history',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_type', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], db_index=True, max_length=3)),
                ('units_available', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('expiry_date', models.DateField(db_index=True)),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('donation_date', models.DateField()),
                ('received_date', models.DateField(auto_now_add=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_quarantined', models.BooleanField(default=False)),
                ('quality_check_passed', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='core.bloodbank')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('bed_capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('has_emergency_ward', models.BooleanField(default=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'HOSPITAL'}, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hospitals',
                'db_table': 'hospitals',
            },
        ),
        migrations.CreateModel(
            name='EmergencyAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_type', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], max_length=3)),
                ('units_required', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('units_allocated', models.PositiveIntegerField(default=0)),
                ('hospital_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('hospital_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('blood_bank_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('blood_bank_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('estimated_time_minutes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('ALLOCATED', 'Allocated'), ('PARTIALLY_ALLOCATED', 'Partially Allocated'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.DateTimeField(blank=True, null=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('allocated_inventory', models.ManyToManyField(related_name='emergency_uses', through='core.AllocationDetail', to='core.inventory')),
                ('blood_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_allocations', to='core.bloodbank')),
                ('demand_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_allocation', to='core.demandhistory')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_requests', to='core.hospital')),
            ],
            options={
                'db_table': 'emergency_allocations',
                'ordering': ['-request_time'],
            },
        ),
        migrations.AddField(
            model_name='demandhistory',
            name='allocated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requests', to='core.emergencyallocation'),
        ),
        migrations.AddField(
            model_name='demandhistory',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_history', to='core.hospital'),
        ),
        migrations.AddField(
            model_name='allocationdetail',
            name='emergency_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_details', to='core.emergencyallocation'),
        ),
        migrations.AddField(
            model_name='allocationdetail',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_details', to='core.inventory'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['blood_bank', 'blood_type'], name='inventory_blood_b_38ec69_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['expiry_date', 'units_available'], name='inventory_expiry__ee864c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['batch_number'], name='inventory_batch_n_eae8fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('blood_bank', 'batch_number')},
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['name'], name='hospitals_name_9e93ed_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['city', 'state'], name='hospitals_city_3b133f_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['is_active'], name='hospitals_is_acti_ff4c80_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyallocation',
            index=models.Index(fields=['hospital', 'status'], name='emergency_a_hospita_2f9b91_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyallocation',
            index=models.Index(fields=['blood_bank', 'status'], name='emergency_a_blood_b_90f6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyallocation',
            index=models.Index(fields=['request_time'], name='emergency_a_request_d0bcfb_idx'),
        ),
        migrations.AddIndex(
            model_name='demandhistory',
            index=models.Index(fields=['hospital', 'request_date'], name='demand_hist_hospita_380864_idx'),
        ),
        migrations.AddIndex(
            model_name='demandhistory',
            index=models.Index(fields=['status', 'priority'], name='demand_hist_status_4c29d3_idx'),
        ),
        migrations.AddIndex(
            model_name='demandhistory',
            index=models.Index(fields=['required_by_date'], name='demand_hist_require_e6e4a3_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodbank',
            index=models.Index(fields=['name'], name='blood_banks_name_b9a59c_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodbank',
            index=models.Index(fields=['bank_type'], name='blood_banks_bank_ty_af3d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodbank',
            index=models.Index(fields=['city', 'state'], name='blood_banks_city_aef37e_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationdetail',
            index=models.Index(fields=['emergency_allocation', 'inventory'], name='allocation__emergen_99cbff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='allocationdetail',
            unique_together={('emergency_allocation', 'inventory')},
        ),
    ]
